### PR TITLE
Move inspection to external_annotator

### PR DESCRIPTION
**Pull request by koxudaxi**
Related issue: 
https://github.com/koxudaxi/ruff-pycharm-plugin/issues/148

@KotlinIsland 
I apply the suggestion to the PR as test.
Could you please test the PR on your machine?
https://intellij-support.jetbrains.com/hc/en-us/community/posts/11275128092690-What-is-the-suggested-pattern-for-implementing-a-plugin-that-runs-an-external-command-that-generates-inspections-

### CODE REVIEW

**Comment by KotlinIsland** [comment]
Amazing, I'll investigate when I have time today.

**Comment by KotlinIsland** [comment]
Two observations:
1. The UI no longer locks for 1 second on every keys
2. The inspections only appear after you pause typing for 5ish seconds.

This fix looks very good, I approve

**Review by KotlinIsland — APPROVED** [review]

**Comment by koxudaxi** [comment]
@KotlinIsland 
Thank you for testing the PR.

> The inspections only appear after you pause typing for 5ish seconds.


I feel a little slow :sweat: 
The change should be optional or default  :thinking:

**Comment by koxudaxi** [comment]
Also, the workaround doesn't use `Inspection`
So, We can't configure the setting in `Editor ->Inspeciton`. :(

**Pull request merged**
